-- DropForeignKey
ALTER TABLE "User" DROP CONSTRAINT "User_companyId_fkey";

-- AlterTable
ALTER TABLE "Company" ALTER COLUMN "email" DROP DEFAULT,
ALTER COLUMN "phone" DROP DEFAULT,
ALTER COLUMN "cep" DROP DEFAULT,
ALTER COLUMN "address" DROP DEFAULT,
ALTER COLUMN "city" DROP DEFAULT,
ALTER COLUMN "state" DROP DEFAULT,
ALTER COLUMN "site" DROP NOT NULL,
ALTER COLUMN "site" DROP DEFAULT,
ALTER COLUMN "complement" DROP NOT NULL,
ALTER COLUMN "complement" DROP DEFAULT,
ALTER COLUMN "about" DROP DEFAULT,
ALTER COLUMN "number" DROP DEFAULT,
ALTER COLUMN "employees" DROP DEFAULT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "companyId" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "User" ADD CONSTRAINT "User_companyId_fkey" FOREIGN KEY ("companyId") REFERENCES "Company"("id") ON DELETE SET NULL ON UPDATE CASCADE;
